# Generated by Django 4.2.15 on 2024-08-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('ds_name', models.CharField(max_length=255, verbose_name='DS')),
            ],
        ),
    ]
