# Generated by Django 4.2.15 on 2024-08-19 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='ou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='ad.organization'),
        ),
    ]
