# Generated by Django 4.2.15 on 2024-08-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_options'),
        ('person', '0002_alter_person_birthday_alter_person_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.position', verbose_name='Должность'),
        ),
    ]
