# Generated by Django 4.2.15 on 2024-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
        ('person', '0004_usergroup_person_ad_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ad_groups',
            field=models.ManyToManyField(blank=True, related_name='persons', through='person.UserGroup', to='ad.group', verbose_name='AD_Группы'),
        ),
    ]
