# Generated by Django 4.2 on 2024-08-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('create_employee', 'Может просматривать компании'),), 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
    ]
