# Generated by Django 4.2 on 2024-08-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('create_employee', 'Может создавать сотрудников'),), 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
    ]
